// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — MoneyPrinter</title><link rel=\"stylesheet\" href=\"/static/css/tailwind.css\"></head><body class=\"min-h-screen bg-background text-foreground\"><!-- Navigation --><nav class=\"border-b border-border\"><div class=\"mx-auto max-w-5xl px-4 flex items-center gap-6 h-14\"><a href=\"/jobs\" class=\"font-bold tracking-tight\">MoneyPrinter</a><div class=\"flex items-center gap-4 text-sm\"><a href=\"/jobs\" class=\"text-muted-foreground hover:text-foreground transition-colors\">Dashboard</a> <a href=\"/drafts\" class=\"text-muted-foreground hover:text-foreground transition-colors\">Drafts</a> <a href=\"/jobs/create\" class=\"text-muted-foreground hover:text-foreground transition-colors\">Create Job</a> <a href=\"/series/create\" class=\"text-muted-foreground hover:text-foreground transition-colors\">Create Series</a></div></div></nav><div class=\"mx-auto max-w-5xl px-4 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><!-- Toast container --><div id=\"toastContainer\" class=\"fixed top-5 right-5 z-50 flex flex-col gap-2\"></div><!-- Shared utilities --><script src=\"/static/js/app.js\"></script><!-- templui component scripts --><script src=\"/static/js/collapsible.min.js\" type=\"module\"></script><script src=\"/static/js/textarea.min.js\" type=\"module\"></script><style>\n\t\t\t\t@keyframes indeterminate {\n\t\t\t\t\t0% { transform: translateX(-100%); }\n\t\t\t\t\t100% { transform: translateX(430%); }\n\t\t\t\t}\n\t\t\t\t.animate-indeterminate {\n\t\t\t\t\tanimation: indeterminate 1.6s ease-in-out infinite;\n\t\t\t\t}\n\t\t\t</style></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
